### ISSUE TITLE
[Feature Request] - Default remote folder for bookmarks

### ISSUE THREAD

**Issue by BackSpace54** [veeso/termscp#100]
## Description

Can you add the possibility to change the remote folder (by default home directory) and/or possibility to navigate in whole file system?

### Changes

When connect the default remote folder is home directory, you can't go up with TermSCP unlike FileZilla, WinSCP or classic SSH cli.
Can you change this?

**Comment by veeso** [comment]
Regarding the possibility to configure the default directory that could be an option for the connection form.

> When connect the default remote folder is home directory, you can't go up with TermSCP unlike FileZilla, WinSCP or classic SSH cli.

This part is not clear to me. You can go wherever you want entering a path with `G` or enter the parent directory with `U`

**Comment by BackSpace54** [comment]
Sorry, my bad for file system navigation with keyboard shortcuts...
Having an option to choose remote folder at connection would be appreciated ;-)
