### ISSUE TITLE
[Feature Request] - ECDSA & EDSA SSH Key Support For SCP

### ISSUE THREAD

**Issue by tuxruffian** [veeso/termscp#103]
## Description

While RSA is still used, it's old, has been subject to several vulnerabilities, and is gradually being phased out in favor of superior cryptography. I would propose support for the following two SSH key types that are supported by OpenSSH, OpenSSL, and GnuTLS:

1. **ECDSA _(ecdsa-sha2-nistp256)_**:  This is the [NIST](https://en.wikipedia.org/wiki/National_Institute_of_Standards_and_Technology) standard for [FIPS](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards) compliant systems.
2. **EDSA _(ed25519)_**:  This high performance implementation is extremely secure and favored by many modern applications. _(e.g. Wireguard, Facebook Messenger, iOS, TOR, WhatsApp, Monero, etc.)_  It will also comply with [FIPS 186-5](https://www.federalregister.gov/documents/2019/10/31/2019-23742/request-for-comments-on-fips-186-5-and-sp-800-186).

**Comment by veeso** [comment]
An analysis has been planned for this feature during the next development cycle.

**Comment by veeso** [comment]
These kinds of keys are already supported by termscp, so there's no need for any kind of implementation. Just paste the private key into the ssh key configuration 😉

**Comment by zdeneksvarc** [comment]
> These kinds of keys are already supported by termscp, so there's no need for any kind of implementation. Just paste the private key into the ssh key configuration 😉

Are you sure? Because still get `authentication failed (could not find any suitable RSA key to authenticate with)` for termscp 0.13.0.
