### ISSUE TITLE
[QUESTION] - Launch termscp from ssh session

### ISSUE THREAD

**Issue by graphixillusion** [veeso/termscp#110]
Hi there. As the title says: is it possible to launch termscp from a ssh session? I've tried to launch the program through a ssh shell into a remote server (Windows 10 OS) but nothing happens. thank you.

**Comment by veeso** [comment]
Hi there,

it works fine here, maybe it's a problem related to the windows terminal. I was able to successfully start it using iterm2 on a linux server.

**Comment by graphixillusion** [comment]
> Hi there,
> 
> it works fine here, maybe it's a problem related to the windows terminal. I was able to successfully start it using iterm2 on a linux server.

I've tried with putty too and i got the same result
