### ISSUE TITLE
AUR package sha265sum mismatch

### ISSUE THREAD

**Issue by tedtms** [veeso/termscp#12]
Hi! Is the 256 checksum still correct in the AUR PKGBUILD for the latest release? I'm getting a conflict. The PKGBUILD says 7a8c70add8306a2cb3f2ee1d075a00fef143fc9aad4199797c7462bab1649296 but I consistently get 04a827ebeac48f0c181617acfa9f2a674e7ac91117a85bf4e68ec6ce31ee4077 when manually downloading from source.

Thanks!

**Comment by veeso** [comment]
Hi! Thanks for reporting this, I totally forgot to update hte sha256 sum in the PKGBUILD.

The installation should now be working for you. If not feel free to reopen the issue.
