### ISSUE TITLE
[Feature Request] - Shift+Tab to reverse panel change direction

### ISSUE THREAD

**Issue by DannyJJK** [veeso/termscp#120]
## Description

Whenever tab is used to change panels, shift+tab should do the same but in reverse order (so it goes backwards instead of forwards). Currently shift+tab does nothing. Many interfaces (GUI and TUI) using the tab key to move, usually allow you to hold down shift to go backwards. It feels unnatural that termscp doesn't allow this.

## Implementation

I think this shouldn't be too difficult to implement. Check if the shift key is pressed down when pressing the tab key, and instead of going to the next panel, go the previous panel.

**Comment by veeso** [comment]
Implemented in 2f1b644a (0.10.0)
