### ISSUE TITLE
[BUG] - On the initial connection form and on the "SSH Keys" section, the shortcut "E" doesn't delete as defined in the Help menu

### ISSUE THREAD

**Issue by DannyJJK** [veeso/termscp#122]
## Description

On the initial connection form and on the "SSH Keys" section, the Help window says:

<DEL|E>         Delete selected bookmark
And
<DEL|E>         Delete SSH key 

I'm using a keyboard which does not have the DEL key, so I must use the E key, however the E key doesn't appear to do anything. I have also tried Shift+E and Ctrl+E as well just in case it was one of those, but they don't work either.

## Steps to reproduce

Open initial connection form, select a bookmark, press E.

Go to config (Ctrl+C), go to SSH keys, select an SSH key (create one if one doesn't exist) and press E.

## Expected behaviour

The bookmark is deleted, probably with a confirmation dialog.

## Environment

- OS: 12.5 (21G72)
- Architecture: Intel
- Rust version: rustc 1.62.1
- termscp version: 0.9.0
- Terminal: alacritty 0.10.1 (2844606)
- Protocol used: N/A
- Remote server version and name: N/A

## Log

I don't know if there's a log of this, but let me know if you need me to provide a log file.

**Comment by veeso** [comment]
Fixed 96df152
