### ISSUE TITLE
[Feature Request] Use id_rsa when password is empty

### ISSUE THREAD

**Issue by Nainterceptor** [veeso/termscp#123]
## Description

I'm able to `ssh` or `scp` to an host using my default id_rsa key.

### Changes

When host is not in termscp ssh key storage, and password is not provided, try to use is_rsa (or previously `ssh-add`ed)

**Comment by veeso** [comment]
That could work with the `IdentityFile` parameter in the ssh configuration actually. If it's ok I put it in my backlog.

**Comment by veeso** [comment]
Implemented IdentityFile check in 64e3848c (0.10.0)
