### ISSUE TITLE
[INSTALLATION] - missing aarch64 linux build

### ISSUE THREAD

**Issue by sjtuross** [veeso/termscp#125]
## Description

I try to install termscp on Raspberry Pi 4B but got the error `Unsupported arch aarch64`. I see arm64-apple-darwin build is available, so I'm wondering if it's possible to publish aarch64 linux build.

## Steps to reproduce

run `curl --proto '=https' --tlsv1.2 -sSLf "https://git.io/JBhDb" | sh` and got the error `Unsupported arch aarch64`

## Expected behaviour

termscp can install on Raspberry Pi 4B.

## Environment

- OS: Ubuntu 22.04
- Architecture: aarch64
- Rust version
- termscp version: 0.9.0
- Protocol used
- Remote server version and name

## Log

```
Unsupported arch aarch64
```

**Comment by Vesther** [comment]
Encountered the same issue on the ARM Macbook, but the homebrew formula works fine on MacOS without those checks, might also be worth the update.

`brew install veeso/termscp/termscp` in case someone with an M1 is looking for it.

**Comment by veeso** [comment]
@Vesther Thanks, I missed a forced exit in the script if the arch wasn't x86_64. Now, M1 installation with sh script should be working fine.

**Comment by veeso** [comment]
It'll be available since 0.11
