### ISSUE TITLE
[BUG] - Unable to install in Rocky Linux 9, failed dependencies: libcrypto.so.10()(64bit)

### ISSUE THREAD

**Issue by albertodiazsaez** [veeso/termscp#127]
## Description

With the provided script the installation fails due to a dependency error.

Execute the installation script: `curl --proto '=https' --tlsv1.2 -sSLf "https://git.io/JBhDb" | sh` Say yes to root access and put your password, then the error occurs.

## Expected behaviour

termscp gets installed correctly on the system.

## Environment

- OS: GNU/Linux Rocky Linux 9
- Architecture x64
- termscp version 0.9.0

## Log

`Termscp configuration
> Platform:      linux
> Arch:          x86_64
? Install termscp 0.9.0? [y/N] y
> Detected rpm on your system
> Installing termscp via RPM package
> Downloaded rpm package to /tmp/tmp.hHwDD33kDi.rpm
! Root permissions are required to install termscp…
> Installing termscp as root, please wait…
error: Failed dependencies:
	libcrypto.so.10()(64bit) is needed by termscp-0.9.0-1.el7.x86_64
	libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit) is needed by termscp-0.9.0-1.el7.x86_64
	libcrypto.so.10(OPENSSL_1.0.2)(64bit) is needed by termscp-0.9.0-1.el7.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by termscp-0.9.0-1.el7.x86_64
	libssl.so.10()(64bit) is needed by termscp-0.9.0-1.el7.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by termscp-0.9.0-1.el7.x86_64
`

## Additional information

In Rocky Linux 9 the only version available for openssl and compat-openssl is 11, and I think termscp requires openssl 10.

**Comment by veeso** [comment]
Duped of #124
