### ISSUE TITLE
[Feature Request] - Import config from `~/.ssh/config`

### ISSUE THREAD

**Issue by sayanarijit** [veeso/termscp#130]
## Description

[SSH config](https://linuxize.com/post/using-the-ssh-config-file/) contain configuration of frequently accessed ssh connections, it can be parsed to set the default config for termscp.

### Changes

The following changes to the application are expected

- Parse and load `~/.ssh/config` by default.

## Implementation

There's no need to support every edge case. Implementation can be done based on priority as set by the community.

- Maybe a separate section (other than bookmarks and recent connections) for the hosts defined in `~/.ssh/config`.
- When connecting to any hosts, respect the authentication config defined in `~/.ssh/config`, unless explicitly defined in termscp.

**Comment by veeso** [comment]
ssh config is already supported, but you need to specify the configuration file from termscp configuration

**Comment by sayanarijit** [comment]
I see, nice. However, I think defaulting to `$HOME/.ssh/config` would be nicer.
