### ISSUE TITLE
[Feature Request] Resuming

### ISSUE THREAD

**Issue by 0-wiz-0** [veeso/termscp#133]
## Description

Please allow transfers to resume if the file already exists.
Even better if it has a default setting.

### Changes

The following changes to the application are expected

- When the file (or directory) already exists, currently a confirmation dialog for "overwriting" exists, this should be extended to add a "resume" option 
- Perhaps add an option to to set a default choice (between overwrite/resume), possibly per connection

**Comment by veeso** [comment]
Implemented to work as:

- if two files have the same mtime (modification time) and size, they're not exchanged in transfer, so this works also as a resume feature.

**Comment by 0-wiz-0** [comment]
I took a look at the diff in #147 and it looks like it implements something slightly different: When a file already exists and has the same metadata, the whole transfer is skipped.

With 'resume' I meant that when a file is partially transferred (e.g. because of network issues or server shutdown, or closing the client too soon) and the file is downloaded again, it should skip the already downloaded part of the file and continue from where it left off; I think right now it always will start at the beginning.
