### ISSUE TITLE
[Feature Request] - Direct transfer to destination path on download.

### ISSUE THREAD

**Issue by TobberH** [veeso/termscp#135]
## Description

It really should transfer and write files directly to local destination path. File downloading to a temp folder has a lot of issues. The program is unusable for large file downloads right now since you always have to have room for the downloaded file in your /tmp folder. It just failed for me on a 5GB file because of this.

Also it is bad for your storage (and performance) to do unnecessary writing to /tmp and then having to wait for data to be moved/written again if the destination folder is on another physical drive and again even worse for big files.

At least make in an option to do direct writing to destination.

### Changes

It should preferably by default write directly to destination folder on downloads.

**Comment by veeso** [comment]
Mhm, I don't know what you're referring to, but it always writes files to the destination path directly.

The only exception is to achieve the COPY command on protocols that don't support it (such as FTP) where the remote file is first downloaded and then re-uploaded to the destination path (and that's also how winscp works).
