### ISSUE TITLE
[BUG] - Project not building using cargo build --locked

### ISSUE THREAD

**Issue by Delta2Force** [veeso/termscp#156]
## Description

The project does not build if you use `cargo build --locked`, which the official script as well as the PKGBUILD on the AUR use.

## Steps to reproduce

`cargo build --locked` after pulling the project

## Expected behaviour

The project was supposed to build without erroring out.

## Environment

- OS: Arch Linux
- Architecture x86_64
- Rust 1.67.1
- termscp 0.11.1
- Protocol used [none]
- Remote server version and name [none]

## Log

```
~/c/termscp (main)> cargo build --locked
    Updating crates.io index
error: the lock file /home/####/coding/termscp/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

## Additional information

I will post a pull request right after this as the fix is extremely simple and short. The only reason I'm writing this issue is to adhere to the Contribution rules.

**Comment by veeso** [comment]
New tag created with fixed lock file
