### ISSUE TITLE
Want to add commands to upload and download files

### ISSUE THREAD

**Issue by shijunti19** [veeso/termscp#159]
## Description
Currently, vscode does not have a very user-friendly ftp software, and the system supports command mode, allowing vscode plug-ins to call

### Changes

The following changes to the application are expected

- ...

## Implementation

Provide any kind of suggestion you propose on how to implement the feature.
If you have none, delete this section.

**Comment by veeso** [comment]
I think this is not in the scope of termscp. It could be a good idea for another project though
