### ISSUE TITLE
[BUG] - could not find RSA key but password provided

### ISSUE THREAD

**Issue by dardevelin** [veeso/termscp#161]
## Description

Attempted to connect to sftp server but refuses due to lack of RSA,
but a password is being used instead. 

## Steps to reproduce

MacOS ventura, fresh install of termscp no changes to any ssh key
server accepts password auth.

## Expected behaviour

to just connect and list files.

Shows error message and does not allow to connect,
does not explain how to "configure such that it works either"

## Environment

- OS: [e.g. GNU/Linux Debian 10]
- MacOS
- Architecture [Arm, x86_64, ...]
- x86_64
- Rust version
- NA (used brew package)
- termscp version
- 0.11.1
- Protocol used
- SFTP
- Remote server version and name
- SFTP protocol version 3 (used ssh with restrictions to sftp connections only under a user)

**Comment by veeso** [comment]
probably related to the issue fixed in 0.12
