### ISSUE TITLE
[BUG] - Install compile failed

### ISSUE THREAD

**Issue by ftaiolivista** [veeso/termscp#162]
==> Starting prepare()...
    Updating crates.io index
error: the lock file /home/vista/.cache/paru/clone/termscp/src/termscp-0.11.1/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'termscp-0.11.1-1':
error: packages failed to build: termscp-0.11.1-1

## Environment

Arch Linux
Linux ws23 6.2.10-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:16 +0000 x86_64 GNU/Linux
rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1)

**Comment by veeso** [comment]
#156 I need to re-create the release...
