### ISSUE TITLE
change keybindings

### ISSUE THREAD

**Issue by marcosiegl** [veeso/termscp#168]
hi veeso, how to change the keybindings in termscp? I would prefer to use the cursor up key to jump to a parent directory and not to switch tabs with it. imho the tab should be reserved to switch between local and remote files panel only. also i would like to have the "e"-key to edit files and not "o" like open. also vi lke keybindings like "h" "j" "k" "l" for navigation would also be a good keybinding choice. I didn't find anything about changing keybindings in the user manual at https://termscp.veeso.dev/#user-manual nor in the help panel or settings. thank you in advance. cheers, marco

**Comment by veeso** [comment]
Unfortunately, it's not possible and currently, I don't have any plans to implement this feature.
