### ISSUE TITLE
[BUG] Still some problems with symlinks

### ISSUE THREAD

**Issue by STPR** [veeso/termscp#17]
Hello,

I've tested your solution for the symlinks hash and backslash characters.
It's better but there are still some problems with symlinks.

Tested with FTP (Pure-FTPd) under Ubuntu and termscp under Windows 10:
- I still can't enter inside symlinks but it works with the Goto command
- I can now browse and enter inside the directories

Tested with SFTP (OpenSSH) under Ubuntu and termscp under Windows 10:
- I can't enter inside symlinks at all and they are now considered like files
  so the Goto command doesn't work
 (I can enter the symlinks using the Goto command without your solution)

**Comment by veeso** [comment]
Merged fixes in 0.4.1
