### ISSUE TITLE
[QUESTION] - allow unknown certificate like filezilla?

### ISSUE THREAD

**Issue by gotbletu** [veeso/termscp#171]
is there an option to allow unknown certificate like filezilla?
or it might be some type of TLS protocol issue im not really sure what it means.

but some FTP/FTPS servers i tried dont work in termscp but works fine in Filezilla because of this

example: 
1. Not Work: termscp fail to connect. sometime i just hangs and gives no error message also on other servers
https://imgur.com/czIc8ZM

2. Works: GUI filezilla works fine after i OK the certificate
https://imgur.com/DdWl8Eg

**Comment by veeso** [comment]
termscp is already configured to accept invalid certificates. The problem seems unrelated. It could be helpful to share the debug log

**Comment by sebma** [comment]
@veeso Found it, on Windows, the debug file is in the `$env:LocalAppdata\termscp\termscp.log`.
