### ISSUE TITLE
[QUESTION] - Can I change file permissions when connecting via SFTP?

### ISSUE THREAD

**Issue by ikocs** [veeso/termscp#172]
I couldn't find the hotkey in the help section. I'm trying to figure out how to change permissions:
![image](https://user-images.githubusercontent.com/10572552/235069271-bf7dc180-12ea-4cd9-854d-ddeaba62118d.png)

**Comment by veeso** [comment]
at the moment there's no such feature, that could be a good feature for the next major.

For the moment you can type `x` and execute `chmod` by yourself

**Comment by ikocs** [comment]
Okay, thank you!

But I am using the Windows version :( 
I can't use `chmod` there

**Comment by veeso** [comment]
the command is executed on the remote, so if the remote server is linux, you can use chmod
