### ISSUE TITLE
[BUG] - Could not parse configuration file: unknown field

### ISSUE THREAD

**Issue by paxsali** [veeso/termscp#173]
Hi all,

I get the error message when trying SFTP or SCP:

```text
IO error (Could not parse configuration file: unknown field: IdentitiesOnly=Yes)
```

I find it strange because I don't understand why termscp would even attempt to parse my `~/.ssh/config`.

This should be left to the environment to (somehow) establish the connection to the remote hosts.

Any idea why this is even necessary?

**Comment by veeso** [comment]
Hi,

enter configuration with `CTRL+C` from main menu and remove ssh config path from it to make termscp not using the ssh configuration.

**Comment by paxsali** [comment]
I copied my `~/.ssh/config` to `~/.ssh/termscp.config`, then removed all `IdentitiesOnly=Yes` from the termscp version. **Now it works.**

I still think it's a bug that this is even necessary.

Termscp shouldn't parse ssh config, IMHO.

**Comment by veeso** [comment]
I'll remove the default config file
