### ISSUE TITLE
[Feature Request] - `brew` installation support for Linux

### ISSUE THREAD

**Issue by farzadmf** [veeso/termscp#174]
## Description

Homebrew is also a valid installation method on Linux, so it would be nice to be able to install `termscp` using `brew` on Linux

### Changes

The following changes to the application are expected

- The Homebrew tap needs to be updated to support Linux

## Implementation

Pretty sure there are examples of this as I use A LOT of Rust libraries that can be installed using `brew` both on Linux and Mac

**Comment by farzadmf** [comment]
Thank you @veeso. Just one thing: I think it would be nice to also include the installation instruction in the `README`.

As it is right now, it's "hidden" inside of the installation script, but you know, sometimes people don't want to go through an installation script to check what it does etc (for security reasons I mean).

It would be nice to have `brew` command directly

**Comment by farzadmf** [comment]
Also, I just tried to `reinstall` on Linux, but seems like it's still installing `0.11.3`

**Comment by veeso** [comment]
It is mentioned in the website, as all the other installation methods.

> Also, I just tried to reinstall on Linux, but seems like it's still installing 0.11.3

You need to wait for 0.12 to be released
