### ISSUE TITLE
[BUG] - No Bookmark Option (C -s)

### ISSUE THREAD

**Issue by no1etal** [veeso/termscp#178]
## Description

Cannot bookmark an FTP or SCP. Ctrl - s not wokring nor do I see such option by checking help.

## Environment

- OS: Ubuntu
- Architecture [x64]
- New Rust
- termscp version 0.11.3

**Comment by veeso** [comment]
from the connection form, CTRL+S currently works on 0.11.3. Are you sure you're trying to save the bookmark from the connection form?

**Comment by no1etal** [comment]
> 

"From the Connection Form", that was it,  much appreciated
