### ISSUE TITLE
[QUESTION] - Does ProxyJump work?

### ISSUE THREAD

**Issue by allencho1222** [veeso/termscp#190]
Hi,

I'm trying to setup termscp using the ssh config file and couldn't find the issues related to `ProxyJump`.

However, while remote hosts without `ProxyJump` work correctly, 
remote hosts with `ProxyJump` cannot successfully access the remote.
(The `scp` command correctly works when accessing the remote hosts crossing the proxy).

Does `ProxyJump` work correctly in termscp?

**Comment by veeso** [comment]
At the moment it's not possible. I don't even know whether it's possible to do that in ssh2-rs, I should ask the authors.
