### ISSUE TITLE
[QUESTION] - Working with Changing File Permissions

### ISSUE THREAD

**Issue by ikocs** [veeso/termscp#191]
Thanks for adding the `chmod` direct change feature in version `0.12.0`!

I have a couple of questions (suggestions) on it:
1. The hot key calls up the window for changing rights, but I don’t understand how to check / uncheck it?

![image](https://github.com/veeso/termscp/assets/10572552/4f2f811f-1b9c-41aa-88cd-02c16b834598)

2. Tips about commands (`F1`) moved out in the help window.
![image](https://github.com/veeso/termscp/assets/10572552/8d5bb485-7982-4be3-8842-285142930b0a)

OS: Window 11
Version termscp: 0.12.0

**Comment by veeso** [comment]
you should be able to do it with `<SPACE>`
