### ISSUE TITLE
[Feature Request] - Scp auto connect to server when server site set the authorized_keys

### ISSUE THREAD

**Issue by iamqk** [veeso/termscp#195]
## Description

Auto connect to server when server site set the authorized_keys without knowing the user's password.
Now you must provide a password to connect to server which cannot work in up situation.

### Changes

- ...

**Comment by iamqk** [comment]
I configure sshconfig to use IdentityFile successfully, and there is another problem:
when
`ConnectTimeout 0`
is set, I think it is means never timeout (in normal terminal it works as this also)
but in termscp it timeout immediately,
I think it means 0 as literally.

**Comment by wxlg1117** [comment]
how to set auto login sftp by authorized_keys ?
