### ISSUE TITLE
[Feature Request] - Allow OPENSSH Key Formats by Default

### ISSUE THREAD

**Issue by TheBrenny** [veeso/termscp#206]
## Description

A couple hours later, and I found out that the reason why I was getting `could not find any suitable RSA key to authenticate with` as an error, was because my `id_rsa` was in `OPENSSH` format, not `RSA` format.

My `id_rsa` was built by a simple `ssh-keygen` command a few years back, so I assume that the `OPENSSH` format is a default of some sort.

For the future Windows users, here's the fix: (just remember to back up your `id_rsa` for safety) `ssh-keygen.exe -p -f .\id_rsa -m pem`.

Similar to #160.

Research: https://superuser.com/questions/1720991/differences-between-begin-rsa-private-key-and-begin-openssh-private-key

### Changes

The following changes to the application are expected

- Allow the use of `OPENSSH` format.

## Implementation

Maybe the crate you're using can do it? Maybe there's a way to detect `OPENSSH` and give the user a command to change it.

**Comment by bravecrayon** [comment]
@TheBrenny Thank you for explaining this
