### ISSUE TITLE
[BUG] - panic if the terminal screen is too small

### ISSUE THREAD

**Issue by lijc210** [veeso/termscp#213]
## Description

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui/activities/auth/mod.rs:209:31

## Steps to reproduce

just run termscp in terminal

## Expected behaviour

display login form page

## Environment

- OS: macbook
- Architecture [m2]
- Rust version: 1.70.0
- termscp version: v0.12.1
- shell: zsh
- Protocol used
- Remote server version and name

**Comment by veeso** [comment]
can you try to run with `RUST_BACKTRACE=full`, please? Otherwise I cannot understand where the panic is, since that is just a function called in many places

**Comment by lijc210** [comment]
> can you try to run with `RUST_BACKTRACE=full`, please? Otherwise I cannot understand where the panic is, since that is just a function called in many places

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui/activities/auth/mod.rs:209:31
stack backtrace:
          0:        0x1051a8e86 - __mh_execute_header
          1:        0x1051ce6cb - __mh_execute_header
          2:        0x1051a363c - __mh_execute_header
          3:        0x1051a8c5a - __mh_execute_header
          4:        0x1051aa6e0 - __mh_execute_header
          5:        0x1051aa490 - __mh_execute_header
          6:        0x1051aac3a - __mh_execute_header
          7:        0x1051aab13- __mh_execute_header
          8:        0x1051a92c9 - __mh_execute_header
          9:        0x1051aa89d - __mh_execute_header
          10:
          11:        0x105200467 - __mh_execute_header
          12:        0x1049cca37 - __mh
          13:        0x104a3236b - __mh_execute_header
          14:        0x1049ce1b3 - __mh_execute_header
          15:
          16:        0x104a07df8 - __mh_execute_header
          17:        0x104a4e5dc - __mh_execu
          18:        0x104a4c720 - __mh_execute_header
          19:        0x104a876c6 - __mh_execute_header
          20:        0x10
          21:        0x10519d452 - __mh_execute_header
          22:        0x104a4f78c - __mh_execute_hea

I found that the terminal can work in full screen mode, but it cannot work in window mode

**Comment by Wonno** [comment]
> I found that the terminal can work in full screen mode, but it cannot work in window mode

I can confirm this behaviour. 

- Local-OS: Windows 11 (Putty - termscp starts only if putty window is maximised) 
- Remote-OS: Debian 12.1

**Comment by veeso** [comment]
> I found that the terminal can work in full screen mode, but it cannot work in window mode

yes, it's true. I will fix it, but anyway at that size termscp isn't supposed to work anyway, it should just display a message to enlarge the window.

**Comment by veeso** [comment]
19992402
