### ISSUE TITLE
[QUESTION] - authentication failed (could not find any suitable RSA key to authenticate with)

### ISSUE THREAD

**Issue by BruceKangCN** [veeso/termscp#217]
I've seen #103 which said ECDSA/EDSA keys are supported now.

I added my EDSA key to SSH keys, then tried to connect to a remote server, but got `authentication failed (could not find any suitable RSA key to authenticate with)`. I also tried locally, with EDSA key it failed but with RSA key it succeeded. I can connect to the remote server or localhost using `OpenSSH` with my EDSA key.

I use `termscp-bin 0.12.1-2` from AUR. I also tried `termscp 0.12.1` from cargo but got the same error.

**Comment by bravecrayon** [comment]
I'm having the same problem

**Comment by tmsmako** [comment]
I have the same issue as well - no luck with a ed25519 private key

**Comment by zdeneksvarc** [comment]
+1, no luck with ed25519 key: `authentication failed (could not find any suitable RSA key to authenticate with)`

**Comment by maskegger** [comment]
+1 any solution to this?
