### ISSUE TITLE
[BUG] - Keys issue and extremely slow UI since 0.12.2

### ISSUE THREAD

**Issue by STPR** [veeso/termscp#219]
Unusable since the 0.12.2.
The keys don't respond correctly and the UI is extremely slow.

**Comment by veeso** [comment]
damn, ratatui doesn't seem to be working on Windows 😮‍💨

**Comment by STPR** [comment]
Thank you 👍
Perhaps that just forcing the versions in the cargo.toml would be better to compile for Windows ?
```rust
lazy-regex = "=2.5"
tui-realm-stdlib = "=1.2"
tuirealm = "=1.8.0"
```

**Comment by STPR** [comment]
I can confirm that it works as well and as fast as before but I needed to change the cargo.toml like in the previous post to compile it for Windows.

**Comment by veeso** [comment]
yeah, it's true. I forgot to commit that change
