### ISSUE TITLE
[BUG] - UI issues in 0.4.1 version on Windows 10

### ISSUE THREAD

**Issue by STPR** [veeso/termscp#22]
termscp is unusable since the 0.4.1 version compiled and used under Windows 10.
Some texts are written outside of the log window and disrupt completly the UI.

**Comment by veeso** [comment]
I've tested the Windows version before the release, but I'm unable to see any of the issues you described. Could you please be more precise of the issues you're having? Could you post a screenshot please?

**Comment by STPR** [comment]
Pure-FTPd under Ubuntu and termscp under Windows 10:

The bug happens just after the connection to the server.
Some texts are written under the log frame (which disrupt the UI)
``
true;Some(Directory(FsDirectory { name: "Files", abs_path: "/home/user1/Files/", last_change_time: SystemTime { intervals: 132610722600000000 }, last_access_time: SystemTime { intervals: 132610722600000000 }, creation_time: SystemTime { intervals: 132610722600000000 }, readonly: false, symlink: None, user: Some(0), group: None, unix_pex: Some((7, 7, 7)) }))
tr> 2021-04-12T21:00:00+04:00 [INFO ]: Established connection with '10.0.0.2': "220 This is a private system - No anonymous login"                                                                                                    _time: SystemTime { intervals: 132610723200000000 }, readonly: false, symlink: None, user: Some(0), group: None, unix_pex: Some((7, 7, 7)) }))
``

I can still browse the directories but it gets even worse and more text is added at the bottom...
Everything return to normal after the deconnection.

**Comment by veeso** [comment]
Damn, I'm really sorry, there was a debugging print on stderr in the ftp file transfer. This was causing the issue only in Windows when connected to a Linux FTP server.

I'm going to release a patch this evening CEST to fix the issue.

**Comment by veeso** [comment]
Issues solved in 0.4.2, which has just been released.
