### ISSUE TITLE
[QUESTION] - How is this so amazing

### ISSUE THREAD

**Issue by Aaronik** [veeso/termscp#220]
I'm a developer, I just hopped onto a new project that uses an ancient sftp / php system, and was struggling to get a good sftp system. There are so many gui apps that are all paid, and don't even have file watching. None of them could integrate cleanly with my nvim editor setup - or at least I couldn't easily figure it out.

I found termscp, and _immediately_ all of my problems were solved.

Thank you so much for your work!

P.S. I didn't know how to tell you this aside from an issue ticket. This isn't really an issue and it's not a question. Please feel free to close this :)

**Comment by veeso** [comment]
Thank you very much for your words ⭐! I felt the same as you a few years ago, so that's why I decided to create termscp.

I look forward to continuing to improve this project, even if I have much less time as before.
