### ISSUE TITLE
cargo build --locked (cannot install nor update)

### ISSUE THREAD

**Issue by no1etal** [veeso/termscp#224]
## Description

cargo build --locked

## Steps to reproduce

yay -S termscp

## Environment

- OS: arch based
- Architecture 64
- Rust 1.73.0
- termscp-0.12.3
- Protocol used

## Log

 yay -S termscp

AUR Explicit (1): termscp-0.12.3-1
:: PKGBUILD up to date, skipping download: termscp
  1 termscp                          (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  1 termscp                          (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
==> Making package: termscp 0.12.3-1 (Thu 26 Oct 2023 13:33:02 CEST)
==> Retrieving sources...
  -> Found termscp-0.12.3.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    termscp-0.12.3.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: termscp
==> Making package: termscp 0.12.3-1 (Thu 26 Oct 2023 13:33:03 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found termscp-0.12.3.tar.gz
==> Validating source files with sha256sums...
    termscp-0.12.3.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting termscp-0.12.3.tar.gz with bsdtar
==> Starting prepare()...
error: the lock file /home/kopachke/.cache/yay/termscp/src/termscp-0.12.3/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: termscp-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
termscp - exit status 4

**Comment by veeso** [comment]
locked flag has been removed
