### ISSUE TITLE
[Feature Request] - Use ssh-agent

### ISSUE THREAD

**Issue by tim-tx** [veeso/termscp#226]
## Description

Based on some tests, I find that `termscp` is unable to handle encrypted ssh keys. Functionality added as a result of #123 and #126 fails when ssh key, e.g. `~/.ssh/id_ed25519`, requires a passphrase.

Usually you would decrypt the key once and make it available to applications via ssh-agent.

If you try to use an encrypted ssh key, you will get this error: `authentication failed (could not find any suitable RSA key to authenticate with)`. Also, in the message, an ssh key need not be an RSA key.

**Comment by alexisfrjp** [comment]
I also don't want to import all my ssh keys...why termscp can't get the keys from the agent like ssh or sftp CLI?

**Comment by kmplngj** [comment]
This would be great. I really want to use my 1Password SSH Agent for this.

**Comment by veeso** [comment]
Will be soon released in 0.14
