### ISSUE TITLE
[BUG] - Transfer fails when terminal app window is moved around

### ISSUE THREAD

**Issue by andris-silis** [veeso/termscp#228]
## Description

When terminal window is moved around or resized, ongoing transfer fails with a message `Could not download file: I/O error on remote: Error waiting on socket`

## Steps to reproduce

- Start a transfer
- Move around (or resize) terminal window

## Expected behaviour

Terminal window moves while transfer is successfully ongoing

## Environment

- MacOs 14.2.1
- Architecture ARM (Apple M2)
- termscp version 0.12.3. Installed using Homebrew
- SCP Protocol
- OpenSSH_9.3p1 Ubuntu-1ubuntu3.2, OpenSSL 3.0.10
- MacOS built-in Terminal app

## Log

`Could not download file: I/O error on remote: Error waiting on socket`

**Comment by veeso** [comment]
I wasn't able to reproduce the issue...
