### ISSUE TITLE
[Feature Request] - SFTP support MFA Code

### ISSUE THREAD

**Issue by lijc210** [veeso/termscp#230]
## Description

termscp SFTP  not supported  MFA Code

❯ sftp -P2222 lijicong@hwops-jumpserver.xxxx.com
lijicong@hwops-jumpserver.xxxx.com's password:
lijicong
Please Enter MFA Code.
(lijicong@hwops-jumpserver.xxxx.com) [OTP Code]:

### Changes

Hope to support MFA Code

**Comment by avoidik** [comment]
you could try `sshotp`, it works the same way as `sshpass`

**Comment by lijc210** [comment]
> you could try `sshotp`, it works the same way as `sshpass`

How to use sshotp in termscp

**Comment by veeso** [comment]
It looks like there's no way to support this with the rust ssh libraries at the moment.
