### ISSUE TITLE
[BUG] - Cannot delete bookmarks

### ISSUE THREAD

**Issue by yudjinn** [veeso/termscp#240]
## Description

Unable to delete bookmarks by hovering over them on the initial screen and pressing either "e" or "DEL" keys.

## Steps to reproduce

1. Save a bookmark
2. hover over bookmark using tab/arrows as necessary
3. press "e" or "DEL" keys

## Expected behaviour

Bookmark is deleted

## Environment

- OS: Linux (Endeavour Galileo Neo)
- Architecture: x86_64
- Rust version: 1.76.0
- termscp version: 0.12.3
- Protocol used: NA
- Remote server version and name: NA

**Comment by veeso** [comment]
I wasn't able to reproduce the issue. They are removed correctly on my machines

**Comment by yudjinn** [comment]
any logs or anything I can send you?

**Comment by veeso** [comment]
Yes, they are at $HOME/.config/termscp/termscp.log
