### ISSUE TITLE
[Feature Request] - Translate Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by shellclear** [veeso/termscp#245]
## Description

Would be interesting to have the README and manual translated to brazilian portuguese.

### Changes

The following changes to the application are expected

- Translate README.md and manual pages to brazilian portuguese

**Comment by veeso** [comment]
That would be great, but unfortunately I can't speak portuguese, so if anyone can contribute, that would be amazing.

**Comment by harturalcantara** [comment]
Hi guys, I did the translation, see if you like it and, when possible, approve it or give me feedback to change it. ;)
