### ISSUE TITLE
[Feature Request] - Better Search Results

### ISSUE THREAD

**Issue by Ktoks** [veeso/termscp#249]
## Description

Add FZF(Fuzzy Finder) to search for files in the directory and its children more efficiently

### Changes

- By pressing CTRL-t - (for example, default fzf implementation) - it would bring up fzf view and allow searching for files to open them or jump to their parent directory.
- By pressing ALT-c - (for example, default fzf implementation) - it would bring up fzf view and allow searching for directories to jump to.

## Implementation

See how Neovim implements fzf.

**Comment by nyabinary** [comment]
It would be extremely nice to have, could use nucleo made by the Helix team.

**Comment by veeso** [comment]
it is partially implemented by this https://github.com/veeso/termscp/issues/256

in 0.15 it will support fuzzy search
