### ISSUE TITLE
[BUG] - Windows SSH Config Ignored

### ISSUE THREAD

**Issue by Ktoks** [veeso/termscp#250]
## Description

Attempting to connect to a remote server that uses a tunnel/jump server, I am unable to connect to the destination server.

## Steps to reproduce

Set up ~/.ssh/config file appropriately - test ssh to server hidden behind tunnel. Upon success - use TermSCP to attempt the same connection - which times out.

## Expected behaviour

Upon connecting to server through tunnel server - the connection should not time out and should be reachable.

## Environment

- OS: Windows
- Architecture: Intel
- Rust version: 1.77.2
- termscp version: 0.13.0
- Protocol used: SFTP, SCP
- Remote server version and name Alma 8

## Log

No logs output.

## Additional information

None

**Comment by giomf** [comment]
I can reproduce this on a linux system. Jusing a jumphost that is configured in my ssh config is not working.

`bad address syntax (failed to lookup address information: Temporary failure in name resolution)`

**Comment by veeso** [comment]
Proxy jumps are not supported with ssh2-rs, so termscp is unable to make them work.

I don't know if this may help https://github.com/veeso/termscp/issues/222#issuecomment-2130178199
