### ISSUE TITLE
[BUG] - SFTP Doesn't Save to Remote

### ISSUE THREAD

**Issue by Ktoks** [veeso/termscp#252]
## Description

Upon opening and saving in my editor, the files do not upload to the server.

## Steps to reproduce

Open any file remotely via TermSCP and make a change, then save. Re-open the file and see that it has not saved.

## Expected behaviour

Upon saving - changes should be uploaded.

## Environment

- OS: Windows 10
- Architecture x86_64 Intel
- Rust version 1.77.2
- termscp version 0.13.0
- Protocol used SFTP
- Remote server version and name Alma 8, Centos 7

## Log

n/a

## Additional information

None

**Comment by veeso** [comment]
I was unable to reproduce on my sftp server. The error message and application logs would be appreciated in case.

**Comment by Ktoks** [comment]
Many apologies for the lengthy response, but after re-installing the latest release - it seems to be working just fine.
Thank you.
