### ISSUE TITLE
[BUG] - README incorrect for AUR install, should we use termscp-bin? 

### ISSUE THREAD

**Issue by bdefore** [veeso/termscp#254]
## Description

README steps direct user to run `pacman -S termscp` but no such package exists.

## Steps to reproduce

Run `pacman -S termscp`

## Expected behaviour

It installs

## Environment

- OS: Manjaro Sway

## Additional information

There is a `termscp-bin` package in AUR. Should the README be updated?

**Comment by veeso** [comment]
Hello @orhun ! Sorry to bother you, do you know why? I've got the same issue actually.

**Comment by orhun** [comment]
The package exists here: https://archlinux.org/packages/extra/x86_64/termscp/

Maybe try running `pacman -Syu termscp`?

**Comment by veeso** [comment]
```sh
❯ sudo pacman -Syu termscp         
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
error: target not found: termscp
```

**Comment by orhun** [comment]
wait a minute...

> OS: Manjaro Sway

I completely missed this detail lol

Arch and Manjaro are [different](https://rentry.co/manjaro-controversies). The package is available in Manjaro Testing, I don't know when it will arrive in Manjaro Stable.

**Comment by veeso** [comment]
Oh you're right, thanks!
