### ISSUE TITLE
[Feature Request] - Deselect all files

### ISSUE THREAD

**Issue by lobneroO** [veeso/termscp#255]
## Description

Ctrl+A selects all files. M toggles selection on the hovered file. There is no way to Deselect all (selected) files).

### Changes

Select all replaced by toggle selection all

## Implementation

Since M toggles the hovered one, probably Ctrl+A should also toggle. If there is a just a subset selected, first Ctrl+A should select all, then if all files are selected, Ctrl+A should deselect all.

**Comment by veeso** [comment]
I will use CTRL+SHIFT+A
