### ISSUE TITLE
[BUG] SFTP cannot handle username with @ symbol

### ISSUE THREAD

**Issue by slapcat** [veeso/termscp#257]
## Description
My username is an email address with an `@` symbol and nearly all functionality with SFTP breaks with that (adding SSH key, removing key, connecting with key). The same server works fine with a username without an `@`.

## Steps to reproduce

This issue affects multiple components of termscp:

1. Add SSH key with hostname `server.com` and user `john.doe@example.com`.
2. Try to delete that SSH key. It will ask to confirm the deletion then doing nothing. Logs show it tries to remove `example.com@john.doe`. The UI shows the key listed as `john.doe at example.com`.
3. Try to connect to `server.com` via SFTP with the SSH key. It will not find the SSH key and say it failed due to bad username/password.

## Expected behaviour

The program can parse a username with an `@` in it and not assume the first term after the `@` is the host.

## Environment

- OS: Debian 12
- Architecture: x86_64
- Rust version: n/a
- termscp version: 0.13.0
- Protocol used: SFTP

**Comment by slapcat** [comment]
This is still an issue. @veeso is this something you could fix?

**Comment by veeso** [comment]
Yes, absolutely. I've planned to make a new release within the next two weeks finally.
