### ISSUE TITLE
[BUG] - Text editor setting not respected

### ISSUE THREAD

**Issue by lobneroO** [veeso/termscp#258]
## Description

In my settings (start termscp -> ctrl+c for setup -> Text editor) I have set to use neovim (/usr/bin/nvim).
When I open a text file (with 'V'), it opens in Notedpad++, so probably using one of my KDE settings.

I tried to use 'W' to force nvim, but that crashed termscp (with both "nvim" and "/usr/bin/nvim" as input)

## Steps to reproduce

In the DE, set some text editor as default for ".txt"
In termscp, create a abc.txt file
In termscp, set a different text editor as your text editor
Open abc.txt with key 'V'

## Expected behaviour

Different text editor is used to open abc.txt

## Environment

- OS: Arch Linux
- Architecture x86_64,
- Rust version 1.78.0
- termscp version 0.13.0
- Protocol used SCP

**Comment by veeso** [comment]
the text editor setting is used when you open a text file the `O` key
