### ISSUE TITLE
[QUESTION] - can termscp be used in command line for automation via scripts?

### ISSUE THREAD

**Issue by suseendare** [veeso/termscp#26]
can termscp be used in command line for automation via scripts? 

I couldn't locate in help on how to transfer or copy a file?

termscp --help 
Usage: termscp [options]... [protocol://user@address:port:wrkdir] [local-wrkdir]

Options:
    -P, --password <password>
                        Provide password from CLI (use at your own risk)
    -T, --ticks <ms>    Set UI ticks; default 10ms
    -v, --version
    -h, --help          Print this menu

**Comment by veeso** [comment]
Hi,

termscp is a terminal ui file transfer, so it isn't meant to be used as a CLI application. Said so, you can't use to automate scripts. If you want to transfer files in automation scripts, the just use `scp` or `ftp` CLI clients.
