### ISSUE TITLE
[BUG] - Stuck in SSH Keys screen when inserting an empty key

### ISSUE THREAD

**Issue by franksl** [veeso/termscp#277]
## Description

When trying to add an ssh key and setting an empty key the application is stuck with a "SSH key is empty!" message without allowing to do almost anything.

## Steps to reproduce
- Configuration -> SSH Keys -> CTRL+N
- add a new empty key
- confirm

Steps to reproduce the bug you encountered

## Environment

Linux

**Comment by veeso** [comment]
fixed in 31c5ad75
