### ISSUE TITLE
[BUG] - Can't save bookmarks

### ISSUE THREAD

**Issue by lelcuk** [veeso/termscp#278]
## Description

on program start, I get an error message 
`Could not initialize bookmarks (at`

after clearing the error the program works as expected, however, I can't save bookmarks

## Steps to reproduce

for me every time I start the program

## Expected behavior

bookmarks can be saved

## Environment

- OS: ubuntu 24.04
- Architecture x86_64
- Rust version 1.80.1
- termscp version 0.14

## Log

2024-09-10T07:04:53.846816392Z [ERROR] Failed to set new key into storage: Provider service error

[termscp.txt](https://github.com/user-attachments/files/16940973/termscp.txt)

**Comment by veeso** [comment]
If it's Ubuntu with gnome gnome-keyring must be installed and accessible to the current user. Otherwise if nothing manages to fix this, just install termscp rebuilding without the keyring feature.
