### ISSUE TITLE
[Feature Request] - folder navigator does not have '..' for changing to parent.

### ISSUE THREAD

**Issue by fcolledani-solari** [veeso/termscp#291]
## Description

When looking at the folders panel, I see something like this:

![immagine](https://github.com/user-attachments/assets/64cd2166-1173-49b4-9165-59b3f92570f2)

### Changes

It would be great to have the '..' link to parent folder. At this moment I need to use the 'change folder command' instead of simply navigating to it.

- ...

**Comment by veeso** [comment]
Just press `U`

**Comment by fcolledani-solari** [comment]
Thanks, but having it in the list would make the UX much better. You can do it by using shortcuts, but you have to remember this. Look at the _gloriously famous_ interface of _Midnight commander_. People normally get used to things they know.

**Comment by lebe-dev** [comment]
I totally agree with @fcolledani-solari. In my opinion, most primary features should have visual controls, while hotkeys can be implicit.

Dots are present in Midnight Commander, Norton Commander, Total Commander, Ranger, etc.

**Comment by veeso** [comment]
https://github.com/veeso/termscp/pull/301
