### ISSUE TITLE
[BUG] - TUI doesn't use the whole pane space

### ISSUE THREAD

**Issue by lebe-dev** [veeso/termscp#305]
## Description

TUI doesn't use all space in panes. It's inconvenient for files with long names.

![image](https://github.com/user-attachments/assets/0d22ddcd-2003-442b-a4f0-b78e8c141c18)

## Steps to reproduce

Open termscp on FullHD screen (1920x1080) and connect to server via smb.

## Expected behaviour

TUI uses all available space for content.

## Environment

- OS: ArchLinux, Wayland, Sway
- Architecture x86_64
- Rust version: rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1)
- termscp version: termscp v0.16.0 (VERGEN_IDEMPOTENT_OUTPUT, VERGEN_I, 2024-10-15T21:08:53.000000000Z) - Developed by Christian Visintin <christian.visintin@veeso.dev>
- Protocol used: SFTP
- Remote server version and name: smbd, Version 4.13.13-Debian
- Screen resolution: 1920x1080

**Comment by veeso** [comment]
It's not really an issue, it's just your font size being too small probably. Anyway, you can configure the explorer syntax to, in case, add other keys in the file line if you really want to fill the space; check the manual.

Why isn't the text justified? Because it's not supported by ratatui.
