### ISSUE TITLE
[BUG] - wrong target arch for arm64-apple-darwin 

### ISSUE THREAD

**Issue by ehjmx** [veeso/termscp#306]
## Description
Calling termscp update on a mac with Apple M processor fails with an error message that no assets are found for the aarch64-apple-darwin

## Steps to reproduce
open a terminal on a mac with an apple m processor. Type `termscp update` wait a few seconds and you get the following output:
`Checking target-arch... aarch64-apple-darwin
Checking current version... v0.15.0
Checking latest released version... v0.16.0
New release found! v0.15.0 --> v0.16.0
New release is *NOT* compatible
Could not install update: ReleaseError: No asset found for target: aarch64-apple-darwin`
In addition a notification is shown with the following message:
`Update installation failed
Release error: No asset found for target:
aarch64-apple-darwin`

## Expected behaviour
that an update is performed

## Environment

- OS: macOS 14.7
- Architecture arm64
- Rust version rustc 1.79.0 (129f3b996 2024-06-10)
- termscp version 0.15

## Log

Report the snippet of the log file containing the unexpected behaviour.
If there is any information you consider to be confidential, shadow it.

## Additional information

github renamend the arch to arm64 for apple-darwin. I had to update this in my scripts as well.

**Comment by veeso** [comment]
fixed in 0.16.1
