### ISSUE TITLE
failed to rebuild 0.16.0 against rust 1.82.0

### ISSUE THREAD

**Issue by chenrui333** [veeso/termscp#307]
seeing some rebuild failure while regression build 0.16.0 against rust 1.82.0

```
  error: unexpected `--cfg unix` flag
    |
    = note: config `unix` is only supposed to be controlled by `--target`
    = note: manually setting a built-in cfg can and does create incoherent behaviors
    = note: `#[deny(explicit_builtin_cfgs_in_flags)]` on by default
```

relates to https://github.com/Homebrew/homebrew-core/pull/194802

**Comment by veeso** [comment]
thanks for reporting. That's a nice breaking change from Rust gg.

69f821ba rebuild from main, please.
