### ISSUE TITLE
[BUG] - Install release 0.16.1 

### ISSUE THREAD

**Issue by scjorge** [veeso/termscp#311]
## Description

Trying to install from Get started page. Install has been broken.

## Steps to reproduce

After execute `curl --proto '=https' --tlsv1.2 -sSLf "https://git.io/JBhDb" | sh` command the script is trying to install 0.16.1 using link `https://github.com/veeso/termscp/releases/download/v0.16.1/termscp_0.16.1_amd64.deb` and this page not exists.

Script dectect my environment correctly

> Platform:      linux
> Arch:          x86_64

## Expected behaviour

just install using Get started page commnad

## Environment

- OS: WSL - GNU/Ubuntu 20.04.6 LTS
- Architecture: x86_64

## Log

```
  Termscp configuration
> Platform:      linux
> Arch:          x86_64

? Install termscp 0.16.1? [y/N] y
> Detected dpkg on your system
> Installing termscp via Debian package
x Command failed (exit code 22): curl --fail --silent --location --output /tmp/tmp.TovsSIchf1.deb https://github.com/veeso/termscp/releases/download/v0.16.1/termscp_0.16.1_amd64.deb
! If you believe this is a bug, please report immediately an issue to <https://github.com/veeso/termscp/issues/new>
```

**Comment by veeso** [comment]
Give me one sec to release...
