### ISSUE TITLE
[Feature Request] - Support PAM Keyboard Interactive Authentication

### ISSUE THREAD

**Issue by Alex-Muirhead** [veeso/termscp#314]
## Description

I would love to use `termscp` with my remote cluster at my university, however they've recently added a 2FA keyboard challenge when connecting via SSH (or others). 

Once an SSH connection attempt is started, an interactive keyboard prompt will ask the user to enter a one-time-password. This step currently can't be handled by `termscp` (as far as I can tell from reading and poking). 

### Changes

It would be great if `termscp` could detect if a prompt was being requested, and create a pop-up prompt (or similar) that forwarded the prompt onto the user. Once the OTP is entered, the connection continues. 

## Implementation

I don't know exactly how to integrate it, but I've seen that the used `ssh2` has a function for [`userauth_keyboard_interactive`](https://docs.rs/ssh2/0.9.4/ssh2/struct.Session.html#method.userauth_keyboard_interactive), which might solve the problem.

**Comment by yocoldle** [comment]
+1 for this, couldn't find a way to use sftp/scp under 2FA
