### ISSUE TITLE
[BUG] - installation with `eget` launches with error: `error while loading shared libraries: libsmbclient.so.0: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by Kenya-West** [veeso/termscp#320]
## Description

I tried to install this binary with [zyedidia/eget](https://github.com/zyedidia/eget), but launching `termscp` leads to error:

```stderr
error while loading shared libraries: libsmbclient.so.0: cannot open shared object file: No such file or directory
```

## Steps to reproduce

1. Install `eget`
2. Run `eget veeso/termscp --asset gnu --to /usr/local/bin`
3. Run `termscp`

## Expected behaviour

`termscp` launches successfully

## Environment

- OS: Ubuntu 24.04
- Architecture x86_64
- Rust version: ???
- termscp version: always latest from GitHub releases (`0.16.1` at this point)
- Protocol used: ??? (`eget` operates through GitHub API, so it should be **HTTPS**)
- Remote server version and name: ???

## Log

`journalctl`:

```log
Dec 14 17:35:57 vm229 sudo[23247]: kenyawest : TTY=pts/3 ; PWD=/home/kenyawest ; USER=root ; COMMAND=/usr/local/bin/termscp
```

**Comment by veeso** [comment]
You must satisfy the requirements. https://github.com/veeso/termscp?tab=readme-ov-file#requirements-

I don't know what eget is, so it may not work.

**Comment by Kenya-West** [comment]
Thanks @veeso for answering! You are right, I somehow missed this section of README. And should not create issues on the midnight when I am tired. Thank again!
