### ISSUE TITLE
[BUG] - Possible to upload a directory that already exists on remote

### ISSUE THREAD

**Issue by Tuuuukka** [veeso/termscp#58]
Is it wanted behavior that you can't upload a directory from local to remote if the directory (with the same name) already exists on the remote server? It is of course more secure this way, but sometimes there's a need to just bulk upload and replace a folder and its contents. Or am I the only one getting an error when trying this?

`[ERROR]: Failed to create directory "/xxxx/xxxxx/xxxxx/xxxxx": Failed to create file ([SFTP(4)] failure)`

**Comment by veeso** [comment]
No, it's a bug actually. That's because I try to create a directory everytime you upload a directory, even if it exists.
I'll fix this asap.
Thanks for reporting this issue!

**Comment by veeso** [comment]
Fixed and merged in 0.6.1, which will be released on the next week
