### ISSUE TITLE
[BUG] - Can't enter @ character in password input box

### ISSUE THREAD

**Issue by BackSpace54** [veeso/termscp#70]
## Description

Can't type @ character in password box

## Steps to reproduce

Set your SSH password with a @ character
Try to input your password in password box
Password is always invalid because @ character is escaped in TUI

## Expected behaviour

Enable @ character as a part of a password and make it inputable in password box

## Environment

- OS: Windows 10 21H1
- Architecture: 64bits
- Rust version: unknow
- termscp version: 0.6.1
- Protocol used: SCP
- Remote server version and name: N/A

## Additional information

FYI it's works if you provide the password with @ character in the CLI with the -P option

Nice app ;-)

**Comment by veeso** [comment]
Thank you very much for reporting the issue (and I'm glad you like termscp 🙂 )!

Fixed in 0.7.0, which will be released on the 12th of october.
