### ISSUE TITLE
[BUG] - Panick message when closing Termscp

### ISSUE THREAD

**Issue by BackSpace54** [veeso/termscp#72]
## Description

When exiting Termscp Windows version got the message:
_thread 'main' panicked at 'Original console mode not set: TryFromIntError(())', C:\Users\chris\.cargo\regist
ry\src\github.com-1ecc6299db9ec823\crossterm-0.20.0\src\event\sys\windows.rs:36:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace_

## Steps to reproduce

Use Termscp Windows version
Open Termscp in native command prompt or WSL
Exiting Termscp with ESC key
Got panick message 

## Expected behaviour

Not having panick message ;-)

## Environment

- OS: Windows 10 21H1
- Architecture: 64bits
- Rust version:
- termscp version: 0.6.1
- Protocol used:
- Remote server version and name:

## Log

Termscp.log attached with RUST_BACKTRACE=1 environment variable set

## Additional information
[termscp.log](https://github.com/veeso/termscp/files/7283655/termscp.log)

**Comment by veeso** [comment]
Thanks again for reporting!
I've already solved this issue in 0.7.0
