### ISSUE TITLE
Using termscp as a dependency fails to compile

### ISSUE THREAD

**Issue by ok-nick** [veeso/termscp#74]
The issue is due to cargo automatically using the latest version of tui-realm-stdlib 0.6.3 where termscp currently requires 0.6.0. tui-realm-stdlib seems to of had a minor update which doesn't respect backwards compatibility.

https://github.com/veeso/tui-realm-stdlib/blob/ecb3f69bb8566dc5d2a4a334bcbafaad07096dea/src/lib.rs#L47
This line is the problem where termscp recognizes the export as public and tui-realm-stdlib has it as private.

**Comment by veeso** [comment]
Hi,

I actually don't know why Cargo.toml takes `0.6.0` as `^0.6.0`, but anyway...
the issue has already been solved in 0.7.0 branch, which is going to be released on the next week. Regarding your PR, feel free to start from 0.7.0 branch and to apply the fixes you made in the CHANGELOG.
