### ISSUE TITLE
[Feature Request] - Parse the SSH config file

### ISSUE THREAD

**Issue by 2b** [veeso/termscp#77]
## Description

Hello. As I see from the description, this project uses `libssh` as the SSH protocol implementation. It would be really nice if termscp could parse the SSH config file and apply SFTP/SCP session settings according to the parsed parameters.

For example, it would allow a public key authentication, control sockets support to speed up connections, a `known_hosts` file support for hosts' keys verification etc.

### Changes

The following changes to the application are expected

- Parse the SSH config file
- Apply SFTP/SCP session settings

## Implementation

https://api.libssh.org/master/group__libssh__session.html

**Comment by veeso** [comment]
Hi,

thank you for reporting this. Yeah it makes perfectly sense, especially considering that the current ssh crate already provides the method to parse the configuration file.

Put in backlog for 0.8.0

See: <https://docs.rs/ssh/0.1.4/ssh/struct.Session.html#method.parse_config>

**Comment by veeso** [comment]
Implementation merged into 0.8.0.
