### ISSUE TITLE
[BUG] Some problems with symlinks, slash and backlash characters

### ISSUE THREAD

**Issue by STPR** [veeso/termscp#9]
Hello,

I'm using Pure-FTPd under Ubuntu 20.10 and termscp 0.4.0 under Windows 10
and there are some problems with symlinks, slash and backlash characters:
```
1- [INFO ]: Established connection with '192.168.1.212': "220 This is a private system"
2- [INFO ]: Changed directory on remote: /Documents
3- [ERROR]: Could not change working directory: Connection error (FTP InvalidResponse: Expected code [250], got response: 553 Prohibited file name: /Documents\HOUSE)
4- [INFO ]: Changed directory on remote: /Documents/HOUSE
```
1- It connects correctly and show correctly the symlink Documents but I can't enter it
2- So I try the Goto command and type Documents and it works
3- Then I try to enter the HOUSE directory but it fails since termscp is sending /Documents\HOUSE instead of /Documents/HOUSE
4- So I try the Goto command again and type /Documents/HOUSE and it works

**Comment by veeso** [comment]
Fixed and merged into `0.4.1`
