### ISSUE TITLE
[Feature Request] - Support Mac M1 chip

### ISSUE THREAD

**Issue by wybert** [veeso/termscp#95]
It can not be installed on my mac book air m1.
will you have a plan to support it?

**Comment by veeso** [comment]
Yes, it's in my plan for the next release, though I need to make the docker file to cross-build on my x86 mac

**Comment by veeso** [comment]
I start to have some doubts on how this thing can be implemented:

- there's no way to run a macos image on docker, so no buildx
- I wasn't able to cross-build with rust, because I need some C libs for arm, such as the libssl so I should check if I'm able to set this up.

**Comment by veeso** [comment]
M1 package be available from 0.8.1
