### ISSUE TITLE
[Feature Request] - Allow S3 compatible storage

### ISSUE THREAD

**Issue by mmack** [veeso/termscp#96]
## Description

Currently only AWS S3 is supported. I would like to use it with - for example - minio.
I think we need to be able to change the endpoint.

See: https://docs.min.io/docs/aws-cli-with-minio.html

**Comment by veeso** [comment]
## Implementation

- [x] Opened PR on remotefs-rs-aws-s3 <https://github.com/veeso/remotefs-rs-aws-s3/pull/1>
- [ ] Released remotefs-aws-s3 0.2.0
- [ ] Implemented new connection parameters to allow custom endpoints on termscp 0.8.1
